phone_checker/urls.py
#
# Copyright (c) 2019, Grigoriy Kramarenko
# All rights reserved.
# This file is distributed under the same license as the current project.
#
from django.urls import path
from phone_checker.views import index, check

app_name = 'phone_checker'


urlpatterns = [
    path('', index, name='index'),
    path('check', check, name='check'),
]

server/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

locale_urlpatterns = [
    path('', include('phone_checker.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns = i18n_patterns(
    path('', include(locale_urlpatterns)),
)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

phone_checker/models.py
#
# Copyright (c) 2019, Grigoriy Kramarenko
# All rights reserved.
# This file is distributed under the same license as the current project.
#
from django.db import models
from django.utils.translation import gettext_lazy as _


class Band(models.Model):
    """Model for band of phone numbers."""
    created = models.DateTimeField(_('created'), auto_now_add=True)
    updated = models.DateTimeField(_('updated'), auto_now=True)
    # Первый номер диапазона.
    first_number = models.BigIntegerField(_('first number'), db_index=True)
    # Последний номер диапазона.
    last_number = models.BigIntegerField(_('last number'), db_index=True)
    # Индексированное кол-во номеров необходимо для сортировки.
    volume = models.IntegerField(_('volume of numbers'), db_index=True)
    # Поле с информацией о месте привязки номеров.
    info = models.TextField(_('information'))
    # Скрытое поле для отличия устаревших записей во время синхронизации с
    # внешними источниками.
    for_upgrade = models.BooleanField(
        default=False, editable=False, db_index=True)

    class Meta:
        verbose_name = _('number band')
        verbose_name_plural = _('number bands')
        unique_together = ('first_number', 'last_number')
        ordering = ('first_number', 'volume')

phone_checker/forms.py
#
# Copyright (c) 2019, Grigoriy Kramarenko
# All rights reserved.
# This file is distributed under the same license as the current project.
#
from django import forms
from django.utils.translation import gettext_lazy as _

from phone_checker.models import Band
from phone_checker.validators import PhoneValidator


class PhoneForm(forms.Form):

    phone = forms.CharField(
        required=True,
        validators=[PhoneValidator()],
        label=_('Enter the phone number'),
        help_text=_(
            'The phone number begins with the " + " sign and contains '
            'only digits. No spaces, hyphens, brackets and other symbols.'
        ),
    )

    def clean_phone(self):
        value = self.cleaned_data['phone']
        try:
            phone = int(value)
        except ValueError:
            raise forms.ValidationError(_('The phone number is not integer.'))
        qs = Band.objects.filter(
            first_number__lte=phone, last_number__gte=phone,
        )
        band = qs.order_by('volume').first()
        if band:
            self.info = band.info
        else:
            raise forms.ValidationError(_('The number is not found.'))
        return '+%s' % phone

phone_checker/views.py
#
# Copyright (c) 2019, Grigoriy Kramarenko
# All rights reserved.
# This file is distributed under the same license as the current project.
#
from django.http.response import JsonResponse
from django.shortcuts import render
from django.views.decorators.cache import cache_page

from phone_checker.forms import PhoneForm


@cache_page(60 * 15)
def index(request):
    """Display interactive form."""

    ctx = {}
    if 'phone' in request.GET:
        form = PhoneForm(request.GET)
        if form.is_valid():
            ctx['phone'] = form.cleaned_data['phone']
            ctx['info'] = form.info
    else:
        form = PhoneForm()
    ctx['form'] = form
    return render(request, 'phone_checker/index.html', ctx)


@cache_page(60 * 15)
def check(request):
    """Check the phone number and returns result as JSON."""

    form = PhoneForm(request.GET)
    if form.is_valid():
        data = {
            'phone': form.cleaned_data['phone'],
            'info': form.info,
        }
    else:
        data = {
            'errors': form.errors.get_json_data(),
        }
    params = {'indent': 2, 'ensure_ascii': False}
    return JsonResponse(data, json_dumps_params=params)

phone_checker/templates/phone_checker/index.html
{% spaceless %}{% load i18n phone_checker_bootstrap4 %}
{% get_current_language as LANGUAGE_CODE %}
{% get_current_language_bidi as LANGUAGE_BIDI %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>{% trans 'Checking the phone number' %}</title>
</head>
<body>
<div class="container">
    <div class="row justify-content-md-center mt-5">
        <div class="col col-md-8 col-lg-6 col-xl-5">
            <div class="card">
                <div class="card-header text-center">
                    <h4 class="mb-0">{% trans 'Phone number checking form' %}</h4>
                </div>
                <div class="card-body">
                    <form class="form" role="form" action="">
                        {{ form.non_field_errors }}
                        {% for hidden in form.hidden_fields %}{{ hidden }}{% endfor %}
                        {% for field in form.visible_fields %}{{ field|form_group }}{% endfor %}
                        <button type="submit" class="btn btn-dark btn-block mt-1">{% trans 'Check' %}</button>
                    </form>
                {% if info %}
                    <div class="alert alert-success mt-2">
                        <h6>{{ phone }}</h6>
                        <p>{{ info|linebreaks }}</p>
                    </div>
                    <div class="text-center">
                        <a href="{% url 'phone_checker:check' %}?{{ request.GET.urlencode }}">JSON</a>
                    </div>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
{% endspaceless %}